### ISSUE TITLE
BSXPCMessage received error for message: Connection interrupted

### ISSUE THREAD

**Issue by dineshjeyasankar** [imgly/imgly-sdk-ios#19]
Hi, I like this sdk a lot. with the latest update i am getting frequent exception "BSXPCMessage received error for message: Connection interrupted" and its slow and crashes on 4s.

**Comment by sascha** [comment]
Hi @dineshjeyasankar,
"BSXPCMessage received error for message: Connection interrupted" is a message, that you can ignore. It's just a warning that the XPC Connection to a service was lost. This is not fatal and the connection will be restored by launchd restarting the service.

The crash most likely happens because we added the possibility to change the intensity of the filters in the live preview. Although we are using the Accelerate framework this is still a computational expensive operation and we might have to remove support for that on older devices. Could you tell me where exactly it crashes and attach a backtrace? Thanks!

**Comment by dineshjeyasankar** [comment]
Thanks. Looks like due to change the intensity of the filters in the live preview.

**Comment by sascha** [comment]
I will push an update tomorrow with better performance. That hopefully fixes the issues with the 4s.

**Comment by dineshjeyasankar** [comment]
If filterIntensity will have some performance impact can we include a way to toggle this on / off?

**Comment by sascha** [comment]
Could you please give 2.1.2 a try? Performance should be improved.

**Comment by dineshjeyasankar** [comment]
Sure. Have been waiting for this over the weekend :) . Will try it.
