### ISSUE TITLE
First text removed

### ISSUE THREAD

**Issue by Spacelapp** [imgly/imgly-sdk-ios#25]
If you add text to an image and try to add a new text after, the first text will be removed.

**Comment by sascha** [comment]
This is a known issue. Currently we only support adding one text item to an image so that you can easily change an already added text again. But we plan to address this issue in a future release where you will be able to add, edit and remove multiple text items and stickers.

**Comment by Spacelapp** [comment]
Multiple stickers are already working...so why not text too?

**Comment by sascha** [comment]
You can add multiple stickers but you can't move them or delete them again afterwards. Both solutions aren't perfect and we are working on a better one that works for text and stickers. I will get back to you early next week with an estimated timeframe.

**Comment by Spacelapp** [comment]
Any news about the fix?

**Comment by sascha** [comment]
Sorry about the delay, we are currently working on a few other features that have higher priority. If you absolutely need this feature, please consider purchasing a commercial license and we can arrange for this fix to be part of the contract. If that is something you are interested in, please contact us via the contact form at http://photoeditorsdk.com and mention this GitHub Issue. Otherwise I'm not able to give you an ETA at the moment unfortunately.

**Comment by K4stor** [comment]
We have implemented the re-edit feature of stickers, will be merged soon.
Text ist on our road map
